import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import store from "./redux/store";
import UserContext from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers store={store}>
        <UserContext>
          <body className={inter.className}>{children}</body>
        </UserContext>
      </Providers>
    </html>
  );
}
